
version: "3.9"
services:
  # Kafka Infrastructure
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: [kong-net]

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: [zookeeper]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "29092:29092"
    networks: [kong-net]

  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    networks: [kong-net]
    ports:
      - "5432:5432"

  kong-migrations:
    image: kong:latest
    depends_on: [kong-database]
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    command: ["kong", "migrations", "bootstrap"]
    networks: [kong-net]

  kong:
    image: kong:latest
    depends_on: [kong-database]
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks: [kong-net]

  micarpeta:
    build: ./micarpeta
    environment:
      PORT: 3000
      KAFKA_BROKER: kafka:9092
      NOTIFICADOR_URL: http://notificador:3003
    ports: ["3000:3000"]
    networks: [kong-net]
    depends_on: [kafka]

  registraduria:
    build: ./registraduria
    environment:
      PORT: 3001
      KAFKA_BROKER: kafka:9092
    ports: ["3001:3001"]
    networks: [kong-net]
    depends_on: [kafka]


  notificador:
    build: ./notificador
    environment:
      PORT: 3003
      KAFKA_BROKER: kafka:9092
    ports: ["3003:3003"]
    networks: [kong-net]
    depends_on: [kafka]

networks:
  kong-net:
    driver: bridge
